
language: node_js
sudo: false
node_js:
  - '7'
install:
  - npm install
script:
  - npm run lint
  - npm run cover
branches:
  only:
  - master
deploy:
  provider: firebase
  token:
    secure: "pfcwLF4C5njiERlKzAdP7GPx6pEGZ1qEOxtpgbEt3ZUluPxg6qiZ7bKbX4PZpueefZsJxzusHgE3xXG/48lFB07sl7Nv3rQgTkFt3Uov5WtUHqvbwugkOsuv74Ir0kzA97N8puSfMiSAeFufL90HH6hnJq0MKeOXL/6rgBGDPgMoopNvNp3Iv7hk2z8w55tR/oKV0Tcq7ReSuyHp55a4rvnZlgau7iBxPiuIMuYzU0SpG83vs2yoEHJFXlPjDb4WgnEuIGjObemomzhY0a1I1NKoeKSmG0HT1Xq6CY+zEdWqORSC5Fc3j5B03+2qHTm0RxDqWPyYydM2Ho4M9te3/BvqPxvdioAU8b432jNueDNFRMGY6yLomLOMk59wnU9Oz3qKO2evXFh89hKGNPcPVAEZmOame5qXJDBkXslzeQ+/zx9aUgZpJHFYaS2nG9XFskQKFOUpAxJLNmPVjdY6WzOTTMKmj2RDMJ5h9J9iRa9ZcA1zvzqUdP7PcfEfUwwhA8vQ3S65lzjW+B3FJsduEmCIB9JejGRcYCyaFJUUte7CHt4DQ/cMDvLL6hPHRevuJf2FoPFmWxel5fPxaRBu8pwoaUKEFcdKh0P3YhCqMT5x2ot9NS0Ycu/MwpjweEpQhh5k0PbMzEDeg1kNoDrd6wqNHFwZzZnq9gZBTz4NDZE="
