language: node_js
sudo: false
node_js:
- '8'
install:
- npm install
- npm install -g firebase-tools
script:
- npm run lint
- npm run cover
- npm run build
- firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
branches:
  only:
  - master
