const SELECT_PRODUCT = 'SELECT_PRODUCT';
const RESET_PRODUCT = 'RESET_PRODUCT';

const START_LOGIN = 'START_LOGIN';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export {
  SELECT_PRODUCT,
  START_LOGIN,
  LOGIN_SUCCESS,
  RESET_PRODUCT
};
